---
docker_monitoring: false

node_exporter_version: '1.7.0'
node_exporter_arch: 'amd64'
node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/\
  node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz"
node_exporter_bin_path: /usr/local/bin/node_exporter
node_exporter_host: "localhost"
node_exporter_port: 9102
node_exporter_options: ''
node_exporter_state: started
node_exporter_enabled: true


cadvisor_version: v0.49.1
cadvisor_bin_path: /usr/local/bin/cadvisor
cadvisor_port: 9101
cadvisor_url: https://github.com/google/cadvisor/releases/download/
cadvisor_download: "{{ cadvisor_url }}/{{ cadvisor_version }}/cadvisor-{{ cadvisor_version }}-linux-amd64"
wer: "https://github.com/google/cadvisor/releases/download/v0.49.1/cadvisor-v0.49.1-linux-amd64"
cadvisor_checksum: >-
  1d5cc701a3fcdf1e8ed1c86da5304b896a6997d9e6673139e78a6f87812495b0

# exporter merger
exporter_merger_version: '0.4.0'
exporter_merger_url: "https://github.com/rebuy-de/exporter-merger/releases/download/\
  v{{ exporter_merger_version }}/exporter-merger-v{{ exporter_merger_version }}.dirty-linux-amd64"
exporter_merger_bin_path: /usr/local/bin/exporter_merger
exporter_merger_port: 9100
